### ISSUE TITLE
keystore / public key

### ISSUE THREAD

**Issue by andineck** [absolutegalaber/jwt-oauth2-example#4]
thank you very much for the example.

how did you create the `jwt-test.jks` keystore and extract the public key `public.cert`? 

I'm trying to create a new keystore / public key, but the validation is not successful.

**Comment by andineck** [comment]
never mind. i figured it out. for reference:

    # generate keystore
    keytool -genkeypair -alias jwt-test -keyalg RSA \
    -dname "CN=jwt,OU=jtw,O=jtw,L=zurich,S=zurich,C=CH" \
    -keypass TODOchange \ 
    -keystore jwt-test.jks \ 
    -storepass TODOchange

    # or in one step: export public key
    keytool -list -rfc --keystore jwt-test.jks | openssl x509 -inform pem -pubkey
    
    # copy paste public key part into public key file: public.cert

**Comment by pschneider-manzell** [comment]
Thanks for the hep text! I added to the main readme file
